# Use the official Ruby image with the latest version
FROM ruby:3.3.3

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    yarn


# Set working directory
WORKDIR /app


# Install gems
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

# Copy the app source code
COPY . .

RUN chmod g+x /app/entrypoint.sh

# Use the script as the entry point
ENTRYPOINT ["/app/entrypoint.sh"]

# Expose port 3000
EXPOSE 3000

# Start the server
CMD ["rails", "server", "-b", "0.0.0.0"]
